name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Linux CPU
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install --yes cmake g++ libgomp1

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --locked --all-targets --no-default-features --features cpu
